env = Environment()
debug = ARGUMENTS.get('debug', 0)

if int(debug):
    env.Append(CCFLAGS = '-g')
else:
    env.Append(CCFLAGS = '-O3')

env.Append(CPPPATH=["../thirdparty/delaunator-cpp/include"])
env.Append(CPPPATH=["../src"])

env.Tool('compilation_db')
env.CompilationDatabase()

env.Program(target="#bin/example", source=['example.cpp', '../src/alpha_model.cpp'])
